### ISSUE TITLE
Tracking breaking changes for v2.0

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2065]
We need to record all noteworthy 2.0 changes as news fragments. Here's the full list: https://github.com/urllib3/urllib3/compare/1.26.x...main. I've listed all relevant changes below. Sorry, this is messy, I sometimes link to the merged commit, and sometimes to the PR. The merged commit is usually a better starting point as Seth usually rewords before merging.

- [x] https://github.com/urllib3/urllib3/commit/fbe9620784b130dcdccf43cd3105940152c4d762 Remove support for Python 2 and 3.5 
- [x] https://github.com/urllib3/urllib3/commit/6af53ac41757399607382bf10a92b288fdf4951d Remove support for Google App Engine Standard
- [x] https://github.com/urllib3/urllib3/commit/b6061f09741082bed3d8b7db10c25bf1ae683a43 Remove strict parameter (but tolerate it in https://github.com/urllib3/urllib3/commit/186e7f91c058d8a04e3b894d5580001e09666ee3)
- [x] https://github.com/urllib3/urllib3/commit/4ff35efb97f68c83b588c0e31d612178776be3d7 Change inner container of HTTPHeaderDict to 'dict' 
- [x] https://github.com/urllib3/urllib3/commit/c67c0949e9c91c7621ea718a7f297ecac7c3b79e Remove deprecated Retry options
- [x] https://github.com/urllib3/urllib3/commit/d39d6a6d01083280554fbe1a240bc85ddd88fdd3 Add BaseHTTPResponse base class 
- [x] https://github.com/urllib3/urllib3/commit/cad4850614d86b4db56a785bc9f984eed342f8be Change return type of HTTPResponse.getheaders() to match CPython
- [x] https://github.com/urllib3/urllib3/commit/c91545052595db80eac46c44d4319a90cc5370a3 Switch to Brotli C bindings for CPython, brotlicffi for non-CPython (#2099)
- [x] https://github.com/urllib3/urllib3/commit/4fadb28df00d0446a1e6b4254050c9ac03958e75 Attach errno to SocketError when raised from OpenSSL.SSL.SysCallError
- [x] https://github.com/urllib3/urllib3/commit/102352a0807c16d8ee3569cfd38be1ca2bfdd7c9 Replace deprecated socket.error with OSError
- [x] https://github.com/urllib3/urllib3/commit/fd0c475cc2c51aedb6c89d7b9be58d850966ee6a + https://github.com/urllib3/urllib3/commit/1bf2f1640f9adbb0a73d8120f7e478b2ce2298f7 Remove commonName support
- [x] https://github.com/urllib3/urllib3/commit/841a7271750b2694589f292e3f395541319a2a44 Use system TLS ciphers if using OpenSSL 1.1.1+ or SecureTransport
- [x] https://github.com/urllib3/urllib3/commit/7d55357d1ed68984043ac8239c7b573ae370844c + https://github.com/urllib3/urllib3/commit/13678970dc9bae35a596310e047aca7c27537181 + https://github.com/urllib3/urllib3/commit/ddf7361ac0467431a2f3df6ba346c9c506c29d56 + https://github.com/urllib3/urllib3/commit/fdea284d89f9ad70c903dec98263160fa4d2a568 + https://github.com/urllib3/urllib3/commit/4953f29c0a0d06572708914cf02e22663e08cf55 Add top-level request() method 
- [x] https://github.com/urllib3/urllib3/issues/1897 Ship our own types 
- [x] https://github.com/urllib3/urllib3/commit/22057712b66eddf48ad3bdf458c1586733508111 Add exception wrapper for HTTPS proxy connection failure (wasn't backported to 1.26.x but probably should have)
- [ ] https://github.com/urllib3/urllib3/commit/7f56f2e7ccdc22faca81f4b41ff7a889e48f3203 Lean on SSLContext to verify hostnames when possible (currently reverted, see https://github.com/urllib3/urllib3/issues/2192 for the versions where it should be enabled)
- [x] https://github.com/urllib3/urllib3/commit/ed23062eef4900f4d4c7540f51062c94bb9dcf07 Fix None/False confusion in is_connection_dropped
- [x] https://github.com/urllib3/urllib3/commit/3346a2a5a7d94e702af49afe77d89d23bf1d0d8a raise FullPoolError if we try to _put_conn an extra connection in blocking mode
- [x] https://github.com/urllib3/urllib3/commit/e208fec114c88e4ea31c60a00b4e8490071fdc1a Fix default socket_options value for HTTPSConnection
- [x] https://github.com/urllib3/urllib3/commit/066ed766de83accb990b86a2b714feec0a32697d Expose HTTPHeaderDict to top level
- [x] https://github.com/urllib3/urllib3/commit/8e8272efda077c5a9f464259bf2a71bb8ec393ad Align multipart parameter encoding with current WHATWG HTML standard 
- [x] Support Python 3.10
- [x] https://github.com/urllib3/urllib3/commit/195b24b1bc692fe95b03f871900e09f2ea19376d Add cycle-breaking logic to create_connection() 
- [x] https://github.com/urllib3/urllib3/commit/1831327b881880ed871f96f56a6977d360042e1b + https://github.com/urllib3/urllib3/commit/8a1ac9f8db13d0673188d542152253d6e133eec9 Raise NameResolutionError instead of socket.gaierror
- [x] https://github.com/urllib3/urllib3/commit/c976e55dfe2bbc0ff8a5ce6c6e9e385f80aa27a4 Remove urllib3.contrib.ntlmpool module
- [x] https://github.com/urllib3/urllib3/commit/ad1712a1d98596a2c9adebd2db4d7eb4d76c36ac Drop support for Python 3.6
- [x] https://github.com/urllib3/urllib3/commit/a04cb71b79c0b7d41f89ec89eab559abc6ca9282 Fix remove_headers_on_redirect feature modifying passed-in headers in-place

Original issue below.

----

We just removed two bits of API in 2.x because they're no longer useful in Python 3:

 * `urllib3.contrib.appengine.AppEngineManager` in #2044
 * the `strict` parameter from `PoolManager`, `ConnectionPool` and `Connection` (currently used by requests) in #2064

Should we:

 1. just put that in the changelog and be done with it?
 2. or make `AppEngineManager` an alias of `PoolManager` and accept but ignore `strict`?

I think we said we were aiming for zero API breakage of that sort, and [@untitaker has mentioned it would help the Sentry SDK](https://github.com/urllib3/urllib3/issues/1944#issuecomment-687597523). I'd be in favor of option 2.

**Comment by sethmlarson** [comment]
- `AppEngineManager` is good to remove since in theory it's impossible to install urllib3 v2.0 on Python 2.7 and that fixture is only usable from Python 2.7
- `strict` is different, because code may have been passing `strict=True` just for the effects on Python 2.7 we should probably just pop it out of `**kwargs` like we were doing before. I'm not sure there's even value in emitting a warning in this case, we can likely just exclude it from type hints to push users away from it. If we want to be more pushy we can emit a `DeprecationWarning` but then it becomes a pain for packages supporting Python 2 still.

**Comment by sethmlarson** [comment]
Unfortunately we'll likely have to handle them on a case-by-case basis. Potentially we can keep this issue open so we can remember how we handled each and that'll help with writing the migration guide.

**Comment by pquentin** [comment]
Another breaking change that should be mentioned in the changelog is [getheaders() return signature changing](https://github.com/urllib3/urllib3/pull/2083/commits/e4fdaf2d8a590dcf1544ffd02fc096a1cc8283a7).

**Comment by sethmlarson** [comment]
Breaking change: [`RecentlyUsedContainer.ContainerCls` is no longer a class property](https://github.com/urllib3/urllib3/pull/2115)

**Comment by sethmlarson** [comment]
Breaking change: Removed `urllib3.util.current_time`, use `time.monotonic` instead (https://github.com/urllib3/urllib3/pull/2214)

**Comment by pquentin** [comment]
We now use towncrier, so I'm going to repurpose that issue to make sure we record all noteworthy v2 changes as news fragments. That way, we won't have to track every change down when we'll actually release 2.0.

**Comment by sethmlarson** [comment]
@pquentin Agreed, would you be willing to tackle that?

**Comment by pquentin** [comment]
Yes, I'm on it! I have 167 commits to review.

**Comment by pquentin** [comment]
I've added 27 potential news fragments to the first comment. Some of them are already in the news fragments, and some of them may turn out to be irrelevant, but that's easier to work with than the original 167 commits :)

**Comment by pquentin** [comment]
Should we turn this into a good first issue? Anyone can add a few news fragments, once merged we can mark them as done above. See https://github.com/urllib3/urllib3/tree/main/changelog for the related documentation.

Or is this something that we should do ourselves?

**Comment by sethmlarson** [comment]
@pquentin We should probably do this ourselves, otherwise it'll be a lot for us to manually review anyways.
