### ISSUE TITLE
Document release checklist

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2307]
### Before creating a release PR

- [x] Announce intent to release on Discord, see if anyone wants to include last minute changes
- [x] Create a `release-X.Y.Z` branch that bumps the version number and updates the changelog
- [x] Create a pull request, see if all tests, including integration, pass

### After creating a release PR

- [x] Get the release pull request approved by a [CODEOWNER](https://github.com/urllib3/urllib3/blob/main/.github/CODEOWNERS)
- [x] Squash merge the release pull request with message "`Release <VERSION>`"
- [x] Tag with X.Y.Z, push tag on urllib3/urllib3 (not on your fork, update `<REMOTE>` accordingly)
  - Notice that the `<VERSION>` shouldn't have a `v` prefix (Use `1.26.6` instead of `v.1.26.6`)
  - ```
    git tag -a '<VERSION>' -m 'Release: <VERSION>'
    git push <REMOTE> --tags
    ```
- [x] Push to PyPI
  - ```
    cd /tmp
    git clone ssh://git@github.com/urllib3/urllib3
    cd urllib3
    git checkout <TAG/VERSION>
    python -m venv
    source venv/bin/activate
    python -m pip install -U pip
    python -m pip install -U twine setuptools wheel
    python setup.py sdist bdist_wheel
    
    twine check dist/*
    # Inspect the output to make sure it looks right
    # Check versions, should be 1 wheel 1 sdist
    
    twine upload dist/*
    ```
- [x] Grab sdist and wheel from PyPI to attach to GitHub release
- [x] Announce on:
  - [x] GitHub releases
  - [x] Twitter
  - [x] Discord
  - [x] OpenCollective
  - [x] GitCoin Grants
- [x] Update Tidelift metadata

**Comment by pquentin** [comment]
I had planned to include this is in the docs, but the way we can tick items directly in UI is awesome. So @sethmlarson suggested that we could add this as an issue template. Which is actually a good first issue!

The idea would be to:
 * take the source of the first comment here
 * untick all checks, eg. change from `[x]` to `[ ]`
 * add a "Open a Release issue from GitHub` step
 * add it to [the `.github/ISSUE_TEMPLATE` directory](https://github.com/urllib3/urllib3/tree/main/.github/ISSUE_TEMPLATE).

**Comment by pquentin** [comment]
Done in #2309
