### ISSUE TITLE
Add support for HTTP/2

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3000]
### Phase 1

- [ ] Ensure our high level test suite (`test_connection`, `test_connectionpool`, `test_poolmanager`) can be used with HTTP/2 connections.
- [ ] Create a new submodule (`urllib3.contrib.http2`) which will house all the logic for implementing HTTP/2
- [ ] Create additions to the existing `BaseHTTPConnection` and `BaseHTTPResponse`, etc that will be needed for HTTP/2 support (`http_version`, `alpn_protocols`)
- [ ] Determine all subtasks for supporting HTTP/2 in issue #3000

### Phase 2

- [ ] Create a new HTTPS connection class which supports HTTP/2 marked as experimental.
- [ ] Ensure this connection class can pass all existing test suites for HTTP connections
- [ ] Connection should manage the socket connection in the background, perhaps through a global connection pool, in order to support background pings/window updates.

### Phase 3

To be determined.

**Comment by sethmlarson** [comment]
Drawing on past successes, @pquentin had the lovely idea to take an incremental approach to starting on HTTP/2. We've identified the test suite and specifically our existing "dummyserver" based on Tornado to be a huge blocker for starting any work related to HTTP/2. In order to get this blocker out of the way so we can start making progress Quentin proposed working on the HTTP/2 test handler for only a single test and then adding tests as we go similar to what we did for type hints.

This approach has advantages beyond unblocking feature and test work, it allows for us to batch test cases that we want to port over to support both HTTP/1 and HTTP/2 piecemeal and using our bounty program instead of trying to land a bunch at once.

My proposal is the following:

- Add an HTTP/2 handler (likely Hypercorn) to the test suite and only use the handler for one test using existing HTTP/1.1
- Add rudimentary HTTP/2 support to urllib3 which uses the test case from above too.
- Add more HTTP/2 handlers and test cases as HTTP/2 support is added.

**Comment by sethmlarson** [comment]
Created a new GitHub milestone for HTTP/2 support: https://github.com/urllib3/urllib3/milestone/10

**Comment by illia-v** [comment]
We've started pursuing a more substantive approach to HTTP/2 support with a designated engineer. As a result, we are not accepting contributions related to the current experimental HTTP/2 implementation at this time.

We also do not have the resources to review the recent influx of related PRs, many of which appear to have been generated primarily with the help of LLMs. We will therefore close all PRs related to the current experimental HTTP/2 feature.

The corresponding issues will remain open for now, but we will remove the bounty labels to avoid encouraging further PR submissions while this work is being reconsidered.

We recognize that withdrawing bounties may be disappointing. However, the [documented](https://urllib3.readthedocs.io/en/2.7.0/contributing.html#getting-paid-for-your-contributions) condition that "*The final say on whether money will be distributed is up to maintainers*" allows us to do so in circumstances such as these.

We will also reform the idea behind bounties in general.
